spring.application.name=Freelanci

# Default profile settings (MySQL for production)
spring.datasource.url=jdbc:mysql://localhost:3306/Freelanci?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

# Enable profiles
spring.profiles.active=@spring.profiles.active@

# Common JPA settings
spring.jpa.open-in-view=false
